# Generated by Django 4.2.4 on 2023-09-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_client', models.CharField(max_length=25, verbose_name='Почта клиента')),
                ('name_client', models.CharField(max_length=20, verbose_name='Имя клиента')),
                ('first_name_client', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия клиента')),
                ('last_name_client', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.TimeField(auto_now_add=True, verbose_name='Время рассылки')),
                ('frequency', models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=10, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('running', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=10, verbose_name='Статус рассылки')),
                ('name_mailing', models.CharField(max_length=10, verbose_name='Название рассылки')),
                ('theme_mess', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('body_mess', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')),
                ('status_log', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество клиента')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера, если он был')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailing', verbose_name='Внешний ключ на рассылку')),
            ],
            options={
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
    ]
