# Generated by Django 4.2.4 on 2023-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='send_time',
            field=models.TimeField(verbose_name='Время рассылки'),
        ),
    ]
