# Generated by Django 4.2.4 on 2023-09-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingLogs',
            new_name='MailingLog',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_mailing_status', 'Can change the status of mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='owner',
            new_name='mailing_owner',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mail_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name_client',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='body_mess',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='client',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='name_mailing',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='theme_mess',
        ),
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия'),
        ),
        migrations.AddField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='body',
            field=models.TextField(default=1, verbose_name='тело письма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='mailing_clients',
            field=models.ManyToManyField(blank=True, null=True, to='main.client', verbose_name='подписчики'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='mailing_status',
            field=models.CharField(choices=[('started', 'Запущена'), ('created', 'Создана'), ('done', 'Завершена')], default='created', max_length=20, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='send_frequency',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default=1, max_length=20, verbose_name='периодичность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='subject',
            field=models.CharField(default=1, max_length=200, verbose_name='тема письма'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing',
            name='send_time',
            field=models.TimeField(verbose_name='время рассылки'),
        ),
    ]
