# Generated by Django 4.2.4 on 2023-09-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mailing_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='send_time',
            field=models.TimeField(default='Не настроено', verbose_name='Время рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('running', 'Запущена'), ('completed', 'Завершена')], default='Создано', max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
