# Generated by Django 4.2.4 on 2023-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_mailinglogs_mailinglog_alter_client_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingLog',
            new_name='MailingLogs',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name_plural': 'Рассылки'},
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='mailing_owner',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='client',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='body',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='mailing_clients',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='mailing_status',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='send_frequency',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='subject',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name_client',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name_client',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='mail_client',
            field=models.CharField(default=1, max_length=25, verbose_name='Почта клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='name_client',
            field=models.CharField(default=1, max_length=20, verbose_name='Имя клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='body_mess',
            field=models.TextField(default=1, verbose_name='Тело письма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(to='main.client'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default=1, max_length=15, verbose_name='Периодичность рассылки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='name_mailing',
            field=models.CharField(default=1, max_length=10, verbose_name='Название рассылки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('running', 'Запущена'), ('completed', 'Завершена')], default='Создано', max_length=15, verbose_name='Статус рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='theme_mess',
            field=models.CharField(default=1, max_length=200, verbose_name='Тема письма'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing',
            name='send_time',
            field=models.TimeField(default='Время в формате Ч:М', verbose_name='Время рассылки'),
        ),
    ]
